---
title: "vEDA"
author: "Allison Randy-Cofie"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Let's import data
```{r}
library(tidyverse)
library(patchwork)
```

## Load the weather data

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10,
    month = lubridate::floor_date(date, unit = "month")) %>%
  select(name, id, everything())

weather_df
```

## `group_by`
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  ungroup()
```


## counting things
count month observations
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n_obs = n()) #name the variable n_obs
```

we can use `count()`
```{r}
weather_df %>% 
  count(month, name = "n_obs")
```

**NEVER** use base R's `table` function
```{r, eval=FALSE}
weather_df %>% 
  pull(month) %>% 
  table() #this result is not a data frame
```


Other helpful counters
```{r}
weather_df %>% 
  group_by(name, month) %>% 
  summarize(n_obs = n(),
            n_days = n_distinct(date))
```


## A digression on 2x2 tables
```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~"cold",
      tmax >=5 ~ "not_cold",
      TRUE ~" "
    )
  ) %>% 
  group_by(name, cold) %>% 
  summarize(count=n())
```


```{r}
weather_df %>% 
  filter(name != "Waikiki_HA") %>% 
  mutate(
    cold = case_when(
      tmax < 5 ~"cold",
      tmax >=5 ~ "not_cold",
      TRUE ~" "
    )
  ) %>% 
  janitor::tabyl(name,cold)
```

